export const FETCH_FORECAST_CURRENT_LOCATION =
  "FETCH_FORECAST_CURRENT_LOCATION";
export const FETCH_FORECAST_SPECIFIED_LOCATION =
  "FETCH_FORECAST_SPECIFIED_LOCATION";

export const CONVERT_CELSIUS = "CONVERT_CELSIUS";
export const CONVERT_FAHRENHEIT = "CONVERT_FAHRENHEIT";
