export const FETCH_FORECAST_CURRENT_LOCATION =
  "FETCH_FORECAST_CURRENT_LOCATION";
export const FETCH_FORECAST_SPECIFIED_LOCATION =
  "FETCH_FORECAST_SPECIFIED_LOCATION";

export const FETCH_CURRENT_LOCATION = "FETCH_CURRENT_LOCATION";
export const FETCH_SPECIFIED_LOCATION = "FETCH_SPECIFIED_LOCATION";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_SPECIFIED_LOCATION = "SET_SPECIFIED_LOCATION";

export const CONVERT_CELSIUS = "CONVERT_CELSIUS";
export const CONVERT_FAHRENHEIT = "CONVERT_FAHRENHEIT";
